### ISSUE TITLE
프로젝트 디자인 및 기능 추가 관련

### ISSUE THREAD

**Issue by shlewislee** [calofmijuck/letter#5]
안녕하세요, thecampy를 사용하셨길래 우연히 보게되었는데 제가 예전부터 하고싶던 프로젝트라 관심이 생겼습니다.
프로젝트가 가능성이 많은 것 같습니다. 저는 백엔드보다는 프론트엔드쪽이 더 익숙해서 좋으시다면 디자인정도 같이 도와드리면서 프로젝트를 좀 더 키울 수 있을 것 같습니다.

**Comment by calofmijuck** [comment]
안녕하세요, 이슈가 등록되어 있었는지 전혀 모르고 있었습니다. 아쉽게도 당장은 조금 어려울 것 같습니다. 관심 가져주셔서 감사합니다! 좋은 하루 되세요!

**Comment by calofmijuck** [comment]
안녕하세요, 이슈가 달려있었는지 전혀 모르고 있었습니다. 이 프로젝트에 관심 가져주셔서 감사합니다. 제가 다른 일들이 많아서 당장은 힘들 것 같아요. 다만 어떤 가능성을 보고 계신지는 좀 더 자세히 논의해보면 재밌을 것 같아요. 이메일 드리겠습니다!
